export type Category = 'Mains'|'Small Chops'|'Sides'|'Rice & Grains'|'Soups'|'Drinks'|'Sweet Treats';
export type Dish = {id:string;name:string;category:Category;price:number;description:string;image:string;dietary?:string[];allergen?:string;serving:string;available:boolean;popular?:boolean;featured?:boolean;spicy?:boolean};
export const categories: Category[]=['Mains','Small Chops','Sides','Rice & Grains','Soups','Drinks','Sweet Treats'];
const photo=(id:string)=>`https://images.unsplash.com/${id}?auto=format&fit=crop&w=900&q=85`;
export const menu: Dish[] = [
{id:'jollof',name:'Smoky Jollof Rice',category:'Rice & Grains',price:13.5,description:'Slow-cooked tomato rice with a gentle smoky finish.',image:photo('photo-1601050690597-df0568f70950'),dietary:['Vegan option'],allergen:'Please ask about ingredients before ordering.',serving:'Generous single portion',available:true,popular:true},
{id:'chicken',name:'Chargrilled Chicken',category:'Mains',price:15.5,description:'Juicy, spice-rubbed chicken grilled until beautifully caramelised.',image:photo('photo-1532550907401-a500c9a57435'),dietary:['High protein'],allergen:'Prepared in a kitchen handling common allergens.',serving:'Half chicken with house sauce',available:true,popular:true,spicy:true},
{id:'fried-rice',name:'Party Fried Rice',category:'Rice & Grains',price:14,description:'Colourful rice with sweet peppers, veg and fragrant seasoning.',image:photo('photo-1512058564366-18510be2db19'),dietary:['Vegetarian option'],serving:'Generous single portion',available:true,popular:true},
{id:'pepper-soup',name:'Goat Pepper Soup',category:'Soups',price:16,description:'A deeply warming broth with tender goat and aromatic spice.',image:photo('photo-1547592180-85f173990554'),dietary:['Spicy'],allergen:'Please ask about ingredients before ordering.',serving:'Large bowl',available:true,spicy:true},
{id:'plantain',name:'Sweet Fried Plantain',category:'Sides',price:4.5,description:'Golden, soft-centred ripe plantain.',image:photo('photo-1601593768799-76c899a49c06'),dietary:['Vegan'],serving:'Sharing side',available:true,popular:true},
{id:'moi-moi',name:'Steamed Moi Moi',category:'Sides',price:5,description:'Silky seasoned bean pudding, steamed the traditional way.',image:photo('photo-1601314002592-b8734bca6604'),dietary:['Vegan','Gluten-conscious'],allergen:'Contains beans; please check suitability.',serving:'One wrapped portion',available:true},
{id:'puff-puff',name:'Puff Puff',category:'Small Chops',price:5.5,description:'Warm, pillowy little dough balls with a delicate sweetness.',image:photo('photo-1551024506-0bccd828d307'),dietary:['Vegetarian'],allergen:'Contains wheat.',serving:'Six pieces',available:true,popular:true},
{id:'meat-pie',name:'Buttery Meat Pie',category:'Small Chops',price:4.75,description:'Flaky pastry filled with warmly seasoned minced beef.',image:photo('photo-1464195244916-7b168e9f0c53'),allergen:'Contains wheat, dairy and egg.',serving:'One large pie',available:true},
{id:'suya',name:'Chicken Suya Skewers',category:'Mains',price:12.5,description:'Tender chicken with a bold peanut-spice crust.',image:photo('photo-1529042410759-befb1204b468'),allergen:'Contains peanuts. Prepared in a shared kitchen.',serving:'Three skewers',available:true,spicy:true},
{id:'egusi',name:'Egusi Soup',category:'Soups',price:15,description:'Rich melon-seed soup with leafy greens and savoury depth.',image:photo('photo-1547592180-85f173990554'),allergen:'Contains melon seeds; please ask about ingredients.',serving:'Large bowl; swallow sold separately',available:true},
{id:'zobo',name:'Hibiscus Zobo',category:'Drinks',price:3.5,description:'Chilled hibiscus, ginger and citrus refresher.',image:photo('photo-1499638673689-79a0b5115d87'),dietary:['Vegan'],serving:'330ml bottle',available:true,featured:true},
{id:'malt',name:'Malt Drink',category:'Drinks',price:3,description:'A classic rich, malty refreshment.',image:photo('photo-1513558161293-cdaf765ed2fd'),serving:'330ml bottle',available:true},
{id:'chin-chin',name:'Cinnamon Chin Chin',category:'Sweet Treats',price:4.5,description:'Crunchy, moreish pastry bites with a cinnamon kiss.',image:photo('photo-1558961363-fa8fdf82db35'),allergen:'Contains wheat and dairy.',serving:'Small sharing bag',available:true},
{id:'coconut-cake',name:'Coconut Cake Slice',category:'Sweet Treats',price:5,description:'Tender vanilla sponge with toasted coconut.',image:photo('photo-1578985545062-69928b1d9587'),allergen:'Contains wheat, dairy and egg.',serving:'One generous slice',available:true},
];
